# Generated by Django 2.0 on 2017-12-07 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_title', models.CharField(max_length=70)),
                ('feed_link', models.URLField(max_length=1024)),
                ('feed_desc', models.CharField(max_length=280)),
                ('item_title', models.CharField(max_length=70)),
                ('item_link', models.URLField(max_length=1024)),
                ('item_desc', models.CharField(max_length=280)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='标签')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='tabs',
            field=models.ManyToManyField(to='fetchfeed.Tabs'),
        ),
    ]
